"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var THREE = require("three");
var hand_1 = require("./hand");
var WIDTH = window.innerWidth;
var HEIGHT = window.innerHeight;
var VIEW_ANGLE = 60;
var ASPECT = WIDTH / HEIGHT;
var NEAR = 0.1;
var FAR = 10000;
var container = document.querySelector('#scene');
var renderer = new THREE.WebGLRenderer();
var camera = new THREE.PerspectiveCamera(VIEW_ANGLE, ASPECT, NEAR, FAR);
var scene = new THREE.Scene();
scene.add(camera);
scene.add(hand_1.getHandMesh());
renderer.setSize(WIDTH, HEIGHT);
renderer.setClearColor(0x000000, 1);
container.appendChild(renderer.domElement);
